[package]
name = "jmdict-codegen"
version = "0.1.0"
edition = "2021"

[lib]
name = "jmdict_codegen"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"
tar = "0.4"