[application]

[web.app]

# HTML title tag content
title = "Japanese Dictionary - JMDict Web App"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["https://cdn.tailwindcss.com"]

# Additional JavaScript files  
script = ["https://cdn.tailwindcss.com"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
